"""initial

Revision ID: 4488f34c9ac0
Revises:
Create Date: 2026-05-28 21:53:50.306757

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "4488f34c9ac0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("webhook_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "payment_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("webhook_url", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_outbox_payment_id"),
        "payment_outbox",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_outbox_published_at"),
        "payment_outbox",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_outbox_status"), "payment_outbox", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_outbox_status"), table_name="payment_outbox")
    op.drop_index(op.f("ix_payment_outbox_published_at"), table_name="payment_outbox")
    op.drop_index(op.f("ix_payment_outbox_payment_id"), table_name="payment_outbox")
    op.drop_table("payment_outbox")
    op.drop_table("payments")
    # ### end Alembic commands ###
